### ISSUE TITLE
Problem with CORS in XMLHttpRequest

### ISSUE THREAD

**Issue by ruv** [hcchengithub/jeforth.3we#4]
Nothing demo from [Play Now](https://github.com/hcchengithub/jeforth.3we#play-now) section is working in Firefox (at least in version 50.0). The following error message is shown: `Error! Failed to read f/jeforth.f`

In the browser console the following error message is shown:
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://raw.githubusercontent.com/hcchengithub/jeforth.3we/master/f/jeforth.f?text. (Reason: CORS preflight channel did not succeed).

**Comment by hcchengithub** [comment]
Thanks for the clear report. 
I guess you were trying to run the 12choc.f game, url is : https://rawgit.com/hcchengithub/jeforth.3we/develop/index.html?include_12choc.f
Or if you were to run jeoforth.3htm without any command then the url is : 
https://rawgit.com/hcchengithub/jeforth.3we/develop/index.html
Both are having the "Error! Failed to read f/jeforth.f" problem on IE and Firefox on Windows 10.
However, they work fine on the Google Chrome browser, right?

So far I noticed that the leading "https://rawgit.com" has been changed to "https://raw.githubusercontent.com/" and that might be the reason violates the  "The Same Origin Policy".

**Comment by ruv** [comment]
The issue is in rawgit.com server. It redirects (via 301) all file with unknown types to raw.githubusercontent.com. For example, it serves https://rawgit.com/hcchengithub/jeforth.3we/master/3htm/js/jeforth.3htm.js but redirects https://rawgit.com/hcchengithub/jeforth.3we/master/3htm/js/jeforth.3htm.js.f
Perhaps this issue should be forwarded to GitHub. CORS should be properly supported in case of such redirects.

**Comment by ruv** [comment]
[rawcdn.githack.com](http://raw.githack.com/) service can be used as temporary workaround. See for example [Box2Dweb Physics Engine demo - Arrows](https://rawcdn.githack.com/hcchengithub/jeforth.3we/master/index.html?cls_include_box2dweb-arrow.f).

**Comment by hcchengithub** [comment]
Ha ha so easy! Thank you very much. 
Now I know some more about the difference between rawgit.com and rawcdn.githack.com. 

I hope that it is possible to say something, e.g. white list of url,  in the index.html to let the browser know what to let go instead of a CORS block.

**Comment by hcchengithub** [comment]
This is the link (faster) to run 12choc.f 
https://rawgit.com/hcchengithub/jeforth.3we/develop/index.html?include_12choc.f
If ```Error! Failed to read f/jeforth.f``` happen on your web browser then this linke (more reliable) :
https://cdn.rawgit.com/hcchengithub/jeforth.3we/develop/index.html?include_12choc.f
should work.
