### ISSUE TITLE
3 of the top 4 demos do not work

### ISSUE THREAD

**Issue by thedanyes** [hcchengithub/jeforth.3we#7]
Solar System, H2O and another demo do not work.

My system:
Ubuntu 20.04.2
Chrome Version 91.0.4472.164 (Official Build) (64-bit)

**Comment by hcchengithub** [comment]
Yeah really! Thank you very much.

**Comment by hcchengithub** [comment]
fixed.

[X] 16:34 2021/03/11 前兩天發現本地的 3ca 例子跑不起來了 (e.g. include h2o.f and include solar-system.f )，應該也是這個問題。
    vm[context].x or vm[current].x 都要改成 tick('x').value.
	14:12 2022/8/2 但是改用 tick() 又會觸發: Warning! private word istar referenced by name in tick()!
	--> See (14:18 2022/8/2): If a word is warned by execute() and tick() then consider to make it public. 
	--> 16:14 2022/8/2 yes, it works! Solar-system.f ok now
	--> 16:24 2022/8/2 h2o.f ok now
	--> 12choc.f
